version: '3.8'

services: 
  nas-website:
    container_name: nas-website
    build:
      context: .
      dockerfile: Dockerfile  # Verweist auf deine Dockerfile, die wir weiter unten anpassen
    volumes: 
      - ./app/:/var/www/html/
      - ./app/nas-website-files/user_files/:/home/nas-website-files/user_files # Datenverzeichnis f체r die Website
      - ./app/nas-website-files/tmp_zips/:/home/nas-website-files/tmp_zips # Datenverzeichnis f체r die tempor채ren Zips
    ports:
      - "80:80"
      - "8443:443"
    restart: unless-stopped
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 59LWrt!mDo6GC4
      MYSQL_DATABASE: nas-website
    networks:
      - nas-network

  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 59LWrt!mDo6GC4
      MYSQL_DATABASE: nas-website
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nas-network

  flask-upload:
    build:
      context: ./flask-upload   # Hier den Ordner angeben, der die Dockerfile enth채lt
      dockerfile: Dockerfile    # Falls deine Dockerfile einen anderen Namen hat, kannst du sie hier spezifizieren
    ports:
      - "8080:5001"
    restart: unless-stopped
    volumes:
      - ./app/nas-website-files/user_files:/uploads
    environment:
      - FLASK_APP=app.py
    networks:
      - nas-network

volumes:
  mysql_data:
  flask-upload-data:

networks:
  nas-network:
    driver: bridge
